---

- name: Install dependencies
  become: yes
  apt: pkg={{item}} state=installed
  with_items:
    - python-pip
  when: pip_command_output.rc != 0

- name: install python packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - {name: 'flask', version: '0.10.1'}
    - {name: 'PyYAML', version: '3.11'}